### ISSUE TITLE
bug: login page sometimes gives empty string to runtime for `name` field???

### ISSUE THREAD

**Issue by dr-frmr** [uqbar-dao/register#7]

**Comment by dr-frmr** [comment]
It appears this happens when you login before giving the FE enough time to decrypt.. need to fix

**Comment by operarotas** [comment]
check - debouncing interval allowed user to hit login button before actual vetting of password was complete, so if they input correct password and logged in, then there would still not be correct username passed because that's set upon decrypting in the rust code and passing back to the frontend after the debouncing period. 

made login button disabled unless the password is verified correct after call to vet keyfile returns
